version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    steps:
      - checkout

      # run tests! and gen code coverage
      - run: mvn integration-test
      - store_artifacts:
          path: target

      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)